### ISSUE TITLE
Feature request: Expose claims, orgs, permissions

### ISSUE THREAD

**Issue by ChrisOgden** [kinde-oss/jwt-validator#3]
### Prerequisites

- [X] I have searched the repository’s issues, [Kinde community](https://thekindecommunity.slack.com/archives/C04K34HUV9B) and [public roadmap](https://updates.kinde.com/board) to ensure my feature request isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### What is the problem you’re trying to solve?

In additional to a quick way to validate a JWT I would like to be able to extract the claims, orgs, permissions that may be included.

### What solution would you like to see?

Add a flag to return details in response signature based on a setting passed into the function or always include a decoded token property on the response.

**Comment by DanielRivers** [comment]
Hi, 

Thanks for your post.  We have a package for decoding the token here: https://github.com/kinde-oss/jwt-decoder is this what you're after?
